vvpd-project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('auth/', include('main.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

vvpd-project/main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

urlpatterns = [
    # URL teacher
    path('teacher/', TeacherView.as_view(), name='teacher'),
    path('teacher/id^<int:pk>/edit/', TeacherUpdateView.as_view(), name="edit_teacher_lk"),
    path('teacher/achievement/view/', AchievementListView.as_view(), name='achievement'),
    path('teacher/achievement/add/', AchievementCreateView.as_view(), name='achievement_add'),
    path('teacher/achievement/get', GetAchievementCreateView.as_view(), name='get_achievement'),
    path('teacher/achievement/id^<int:pk>/edit/', AchievementUpdateView.as_view(), name='edit_achievement'),
    path('teacher/achievement/id^<int:pk>/del/', AchievementDeleteView.as_view(), name='del_achievement'),
    path('teacher/student/add/', StudentCreateView.as_view(), name='student_add'),
    path('teacher/group/add/', GroupCreateView.as_view(), name='group_add'),
    path('teacher/work/add/', WorkCreateView.as_view(), name='work_add'),
    path('teacher/work/^<int:pk>/delete/', WorkDeleteView.as_view(), name='delete_work'),
    path('teacher/work/^<int:pk>/edit', WorkUpdateView.as_view(), name='update_work'),
    path('teacher/work/all/', WorkListView.as_view(), name='work'),
    path('teacher/group/all/', GroupListView.as_view(), name='group'),
    path('teacher/student/all/', StudentListView.as_view(), name='student_view'),
    path('teacher/student/^<int:pk>/info/', StudentDetailView.as_view(), name='student_detail'),
    path('teacher/student/^<int:student_id>/info/id^<int:pk>/edit/', GradeWorkUpdateView.as_view(), name='grade_work_edit'),
    path('teacher/student/^<int:student_id>/info/^<int:work_id>/grade/', GradeWorkCreateView.as_view(), name='grade_work'),

    # URL student
    path('student/id^<int:pk>/edit/', StudentUpdateView.as_view(), name="edit_student_lk"),
    path('student/', StudentView.as_view(), name='student'),
]

vvpd-project/main/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import (MaxValueValidator, MinValueValidator,
                                    RegexValidator)
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from PIL import Image


TYPE_USERS = [
    ("student", 'Студент'),
    ("teacher", 'Преподаватель')
]


TYPE_FORM_OF_EDUCATIONS = [
    (None, ''),
    ('очная', 'Очная'),
    ('заочная', 'Заочная')
]


class User(AbstractUser):
    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    first_name = models.CharField("Имя", max_length=100)
    last_name = models.CharField("Фамилия", max_length=100)
    middle_name = models.CharField("Отчество", max_length=100, blank=True)
    user_status = models.CharField(
        "Статус", choices=TYPE_USERS, max_length=100)

    def get_full_name(self):
        return f'{self.last_name} {self.first_name} {self.middle_name}'

    get_full_name.short_description = 'Ф.И.О.'


class Teacher(models.Model):
    class Meta:
        verbose_name = "Предподаватель"
        verbose_name_plural = "Предподаватели"

    user = models.OneToOneField(
        User, verbose_name="Аккаунт", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'


class Student(models.Model):
    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"

    user = models.OneToOneField(
        User, verbose_name="Аккаунт", on_delete=models.CASCADE)
    group = models.ForeignKey(
        "Group", verbose_name="Группа", on_delete=models.CASCADE)
    form_of_education = models.CharField(
        "Форма обучения", max_length=7, choices=TYPE_FORM_OF_EDUCATIONS, default='очная')
    link_vk = models.URLField("Ссылка на ВК", blank="True")
    link_gitlab = models.URLField("Ссылка на gitlab", blank="True")

    def __str__(self):
        return f'{self.user.get_full_name()} {self.group}'


class Group(models.Model):
    name = models.CharField("Название группы", max_length=60, unique=True)
    year_of_enrollment = models.CharField("Год зачисления", max_length=4, validators=[
                                          RegexValidator("^[2][0-9]{3}$", message="Неверный формат ввода года")])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"


class Work(models.Model):
    name = models.CharField(
        max_length=150, verbose_name="Название работы", unique=True)
    description = models.TextField(verbose_name="Описание")
    dedline = models.DateTimeField('Дедлайн')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Практическая работа"
        verbose_name_plural = "Практические работы"


class Achievement(models.Model):
    name = models.CharField("Название достижения", max_length=70, unique=True)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="static/img/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('achievement', kwargs={'pk': self.user_id})

    def save(self, *args, **kwargs):
        super(Achievement, self).save(*args, **kwargs)

        MAX_SIZE = 100

        if self.image:
            filepath = self.image.path
            width = self.image.width
            height = self.image.height

            max_size = max(width, height)

            if max_size > MAX_SIZE:
                image = Image.open(filepath)
                image = image.resize(
                    (round(width / max_size * MAX_SIZE),
                     round(height / max_size * MAX_SIZE)),
                    Image.ANTIALIAS
                )
                image.save(filepath)

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        super(Achievement, self).delete(*args, **kwargs)
        storage.delete(path)

    class Meta:
        verbose_name = "Достижение"
        verbose_name_plural = "Достижения"


class GetAchievement(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, verbose_name="Студент")
    achievement = models.ForeignKey(
        Achievement, on_delete=models.CASCADE, verbose_name="Достижение")
    issued_on_hand = models.BooleanField("Выдана студенту", default=False)

    def __str__(self):
        return f'{self.achievement} выдана {self.student}'

    class Meta:
        unique_together = ('student', 'achievement')


class Grade(models.Model):
    grade = models.PositiveSmallIntegerField("Оценка за дедлайн", validators=[
                                             MaxValueValidator(100), MinValueValidator(0)])
    grade_for_protection = models.PositiveSmallIntegerField("Оценка за защиту", validators=[
        MaxValueValidator(100), MinValueValidator(0)])
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    comment = models.TextField("Комментарий", blank=True)
    date_of_delivery = models.DateTimeField("Дата сдачи", default=timezone.now)

    class Meta:
        unique_together = ('student', 'work')
        verbose_name = "Оценка"
        verbose_name_plural = "Оценки"

vvpd-project/main/views.py
from config.permissions import StudentPermissionsMixin, TeacherPermissionsMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, FormView, ListView,
                                  TemplateView, UpdateView, DetailView, View)

from .forms import *
from .models import *


class TeacherView(LoginRequiredMixin, TeacherPermissionsMixin, View):
    def get(self, request):
        return render(request, 'teacher_lk.html')


class StudentView(LoginRequiredMixin, StudentPermissionsMixin, View):
    def get(self, request):
        return render(request, 'student_lk.html')


class AchievementListView(LoginRequiredMixin, TeacherPermissionsMixin, ListView):
    model = Achievement
    template_name = 'achievement.html'
    context_object_name = 'achievements'


class AchievementCreateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, CreateView):
    form_class = FormAddAchievement
    template_name = 'add_achievement.html'
    success_url = reverse_lazy('achievement_add')
    success_message = "Достижение '%(name)s' было успешно добавленно!"

    def post(self, request, *args, **kwargs):
        form = FormAddAchievement(self.request.POST, self.request.FILES)
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.render_to_response({'form': form})


class AchievementUpdateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, UpdateView):
    model = Achievement
    form_class = FormUpdateAchievement
    template_name = 'edit_achievement.html'
    success_message = "Достижение было успешно обновленно!"

    def get_success_url(self):
        return reverse_lazy('edit_achievement', kwargs={'pk': self.kwargs['pk']})


class AchievementDeleteView(LoginRequiredMixin, TeacherPermissionsMixin, DeleteView):
    model = Achievement
    template_name = 'del_achievement.html'
    success_url = reverse_lazy('achievement')


class GetAchievementCreateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, CreateView):
    form_class = FormGetAchievement
    template_name = 'get_achievement.html'
    success_message = "Достижение '%(achievement)s' было успешно выдано '%(student)s!'"
    success_url = reverse_lazy('get_achievement')

    def post(self, request, *args, **kwargs):
        form = FormGetAchievement(self.request.POST)
        students = Student.objects.all()
        groups = Group.objects.all()
        if form.is_valid():
            return self.form_valid(form)
        else:
            messages.error(
                request, 'Что-то пошло не так, попробуйте снова!')
            return self.render_to_response({'form': form, 'students': students, 'groups': groups})

    def get_context_data(self, **kwargs):
        data = super(GetAchievementCreateView, self).get_context_data(**kwargs)
        data['students'] = Student.objects.all()
        data['groups'] = Group.objects.all()
        return data


class StudentUpdateView(LoginRequiredMixin, StudentPermissionsMixin, SuccessMessageMixin, UpdateView):
    model = User
    template_name = 'edit_student_lk.html'
    success_message = "Ваш профиль успешно обновлен!"
    form_class = StudentUpdateForm
    initial = {}

    def get_initial(self):
        base_initial = super().get_initial()
        base_initial['link_vk'] = Student.objects.get(
            user__pk=self.request.user.pk).link_vk
        base_initial['link_gitlab'] = Student.objects.get(
            user__pk=self.request.user.pk).link_gitlab
        return base_initial

    def get_success_url(self):
        return reverse_lazy('edit_student_lk', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['second_model'] = Student.objects.get(
            user__pk=self.request.user.pk
        )
        return context

    def form_valid(self, form):
        link_vk = form.cleaned_data.get('link_vk', None)
        link_gitlab = form.cleaned_data.get('link_gitlab', None)
        if link_vk or link_gitlab:
            instance = self.get_context_data().get('second_model')
            instance.link_vk = link_vk
            instance.link_gitlab = link_gitlab
            instance.save()
        return super().form_valid(form)


class TeacherUpdateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, UpdateView):
    model = User
    template_name = 'edit_teacher_lk.html'
    success_message = "Ваш профиль успешно обновлен!"
    form_class = TeacherUpdateForm

    def get_success_url(self):
        return reverse_lazy('edit_teacher_lk', kwargs={'pk': self.kwargs['pk']})


class StudentCreateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'add_student.html'
    success_url = reverse_lazy('student_add')
    success_message = 'Cтудент успешно добавлен'

    def get_context_data(self, **kwargs):
        data = super(StudentCreateView, self).get_context_data(**kwargs)
        data['student_form'] = StudentForm()
        return data

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        student_form = StudentForm(self.request.POST)
        if form.is_valid() and student_form.is_valid():
            user = form.save(commit=False)
            user.user_status = 'student'
            student = student_form.save(commit=False)
            student.user = user
            user.save()
            student.save()
            return self.form_valid(form)
        else:
            return self.render_to_response({'form': form, 'student_form': student_form})


class GroupCreateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, CreateView):
    form_class = GroupCreateForm
    template_name = 'add_group.html'
    success_message = 'Группа успешно добавлена'
    success_url = reverse_lazy('group_add')


class WorkCreateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, CreateView):
    form_class = WorkCreateForm
    template_name = 'add_work.html'
    success_message = 'Практическая работа успешно добавлена'
    success_url = reverse_lazy('work_add')


class WorkListView(LoginRequiredMixin, TeacherPermissionsMixin, ListView):
    model = Work
    template_name = 'work.html'
    context_object_name = 'works'


class GroupListView(LoginRequiredMixin, TeacherPermissionsMixin, ListView):
    model = Group
    template_name = 'group.html'
    context_object_name = 'groups'


class StudentListView(LoginRequiredMixin, TeacherPermissionsMixin, ListView):
    model = Student
    template_name = 'student.html'
    context_object_name = 'students'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.all()
        context['years'] = set(
            [x.year_of_enrollment for x in Group.objects.all()]
        )
        return context


class StudentDetailView(LoginRequiredMixin, TeacherPermissionsMixin, DetailView):
    template_name = 'student_detail.html'

    def get_queryset(self):
        queryset = User.objects.select_related(
            'student__group').filter(user_status='student')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['works'] = Work.objects.all()
        context['grades'] = Grade.objects.filter(student__user=context['user'])
        context['work_grade'] = [x.work for x in Grade.objects.filter(
            student__user=context['user'])]
        return context


class GradeWorkCreateView(LoginRequiredMixin, TeacherPermissionsMixin, CreateView):
    template_name = 'grade_work.html'
    form_class = GradeWorkCreateForm

    def post(self, request, student_id, work_id, *args, **kwargs):
        form = GradeWorkCreateForm(self.request.POST)
        if form.is_valid():
            forms = form.save(commit=False)
            forms.student = Student.objects.get(user__id=student_id)
            forms.work = Work.objects.get(id=work_id)

            # Расчет оценки за дедлайн: 1 нелеля - 10 баллов
            dedline = Work.objects.get(id=work_id).dedline
            date_of_delivery = forms.date_of_delivery
            grade_work = int(str(date_of_delivery - dedline).split()[0])

            if grade_work > 0:
                if (100 - abs(grade_work // 6) * 10) < 0:
                    forms.grade = 0
                else:
                    forms.grade = (100 - abs(grade_work // 6) * 10)
            else:
                forms.grade = 100
            form.save()
            return self.form_valid(form)

        return self.render_to_response({'form': form})

    def get_success_url(self):
        return reverse_lazy('student_detail', kwargs={'pk': self.kwargs['student_id']})


class GradeWorkUpdateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, UpdateView):
    model = Grade
    template_name = 'update_student_grade.html'
    success_message = "Оценка за практическую работу успешно обновлена!"
    form_class = GradeUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student_id'] = self.kwargs['student_id']
        return context

    def get_success_url(self):
        return reverse_lazy('grade_work_edit', kwargs={'student_id': self.kwargs['student_id'], 'pk': self.kwargs['pk']})


class WorkUpdateView(LoginRequiredMixin, TeacherPermissionsMixin, SuccessMessageMixin, UpdateView):
    model = Work
    form_class = WorkUpdateForm
    template_name = 'work_update.html'
    success_message = "Практическая работа успешно обновлена!"

vvpd-project/main/templates/achievement.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Достижения{% endblock %}

{% block content-header %}
<h3 class="text-center">Просмотр всех достижений</h3>
{% endblock %}

{% block content %}

{% if achievements %}
<p class="text-center"><i class="fa fa-info-circle" aria-hidden="true"></i> Наведите на иконку, чтобы посмотреть условия получения достижения.</p>
<div class="item">
    {% for achievement in achievements %}
    <div class="iconblock">
        <div title="{{ achievement.description }}" class="icon">
            <img class="img" src="{{ achievement.image.url }}" />
        </div>
        <div>
            <h3>{{ achievement.name }}</h3>
        </div>
        <div class="act-in-achievement">
            <a class="update-achievement btn btn-sm btn-primary" href="">
                <span class="fa fa-edit"></span>
            </a>
            <a class="delete-achievement btn btn-sm btn-danger" href="">
                <span class="fa fa-trash"></span>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p class="text-center">На данный момент не созданно ни одно достижение!</p>
{% endif %}
{% endblock %}

{% block script %}
<script>
    $("#search").on("keyup", function () {
        var inputValue = $(this).val().toLowerCase();
        var count = 0
        $("#achievement-table tbody tr").filter(function () {
            if ($(this).children('.name').text().toLowerCase().indexOf(inputValue) > -1) count++;
            $(this).toggle($(this).children('.name').text().toLowerCase().indexOf(inputValue) > -1)
        });
        if (count == 0) {
            $('.error-search').show();
        } else {
            $('.error-search').hide();
        }
    });
</script>
{% endblock %}

vvpd-project/main/templates/add_group.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Добавить группу{% endblock %}

{% block content-header %}
<h3 class="text-center">Добавить группу</h3>
{% endblock %}

{% block content %}

{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert alert-success text-center" role="alert">
        {{ message }}
    </div>
</div>
{% endfor %}

<div class="col-12 col-md-6 offset-md-3">
    <form class="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-5">
            {{ form.name|as_crispy_field }}
            <br>
            {{ form.year_of_enrollment|as_crispy_field }}
        </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success">Добавить</button>
            &nbsp;
            <a class="btn btn-secondary" href="{% url 'teacher' %}" class="">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    var info_messages = document.getElementsByClassName('alert-success');
    setTimeout(function () {
        for (var i = 0; i < info_messages.length; i++) {
            info_messages[i].setAttribute('style', 'display:none !important');
        }
    }, 3000);
</script>
{% endblock %}

vvpd-project/main/templates/add_student.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Добавить студента{% endblock %}

{% block content-header %}
<h3 class="text-center">Добавить студента</h3>
{% endblock %}

{% block content %}

{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert alert-success text-center" role="alert">
        {{ message }}
    </div>
</div>
{% endfor %}

<div class="col-12 col-md-6 offset-md-3">
    <form class="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <h3>Логин и пароль</h3>
            <hr>
            {{ form.username|as_crispy_field }}
            {{ form.password|as_crispy_field }}
        </div>
        <div class="mb-3">
            <h3>Личные данные</h3>
            <hr>
            {{ form.last_name|as_crispy_field }}
            {{ form.first_name|as_crispy_field }}
            {{ form.middle_name|as_crispy_field }}
        </div>
        <div class="mb-3">
            <h3>Группа и форма обучения</h3>
            <hr>
            {{ student_form.group|as_crispy_field }}
            {{ student_form.form_of_education|as_crispy_field }}
        </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success">Добавить</button>
            &nbsp;
            <a class="btn btn-secondary" href="{% url 'teacher' %}" class="">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        $('#id_group').select2({
            placeholder: "",
            width: '100%',
        });
    });

    $(document).on("select2:open", () => {
        document.querySelector(".select2-container--open .select2-search__field").focus()
    })

    var info_messages = document.getElementsByClassName('alert-success');
    setTimeout(function () {
        for (var i = 0; i < info_messages.length; i++) {
            info_messages[i].setAttribute('style', 'display:none !important');
        }
    }, 3000);
</script>
{% endblock %}

vvpd-project/main/templates/del_achievement.html
{% extends 'base.html' %}

{% block title %}Удалить достижение{% endblock %}

{% block content-header %}
<h3 class="text-center">Удалить достижение</h3>
{% endblock %}
{% block content %}
<div class="col-12 col-md-6 offset-md-3 text-center">
    <form class="" method="post">
        {% csrf_token %}
        <p><i class="fa fa-info-circle" aria-hidden="true"></i> Вы действительно хотите удалить данное достижение?</p>
        <br>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success">Удалить</button>
            &nbsp;
            <a class="btn btn-secondary" href="{% url 'achievement' %}" class="">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

vvpd-project/main/templates/edit_achievement.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Редактировать достижение{% endblock %}


{% block content-header %}
<h3 class="text-center">Редактировать достижение "{{ achievement.name }}"</h3>
{% endblock %}

{% block content %}

{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert alert-success text-center" role="alert">
        {{ message }}
    </div>
</div>
{% endfor %}

<div class="col-12 col-md-6 offset-md-3">
    <form class="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-5">
            {{ form.name|as_crispy_field }}
            {{ form.description|as_crispy_field }}
            {{ form.image|as_crispy_field }}
            <p class='label-info' id="upload-file-info">Текущее фото: {{ form.image.value }}</p>
        </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success">Сохранить</button>
            &nbsp;
            <a class="btn btn-secondary" href="{% url 'achievement' %}" class="">Назад</a>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    var info_messages = document.getElementsByClassName('alert-success');
    setTimeout(function () {
        for (var i = 0; i < info_messages.length; i++) {
            info_messages[i].setAttribute('style', 'display:none !important');
        }
    }, 3000);
</script>
{% endblock %}

vvpd-project/main/templates/get_achievement.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Выдать достижение{% endblock %}

{% block content-header %}
<h3 class="text-center">Выдать достижение</h3>
{% endblock %}

{% block content %}

{% for message in messages %}
<div class="container-fluid p-0">
    <div {% if message.tags %} class="alert {{ message.tags }} text-center" role="alert" {% endif %}>
        {{ message }}
    </div>
</div>
{% endfor %}

<form class="" method="post">
    {% csrf_token %}
    <div class="col-12 col-md-10 offset-md-1">
        <p><i class="fa fa-info-circle" aria-hidden="true"></i> Выберите студента и достижение и нажмите кнопку "Выдать"
        </p>
        {{ form.achievement|as_crispy_field }}
        <br>
        <div class="nav-menu" style="display:flex;">
            <input type="text" class="form-control" id="search" placeholder="Поиск по ФИО..."
                style="margin-right: 13px;">
            <select id="name-group" class="select-student" style="margin-right: 10px;">
                <option value="">Группа</option>
                {% for group in groups %}
                <option value="{{ group }}">{{ group }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="table-wrapper-scroll-y scrollbar">
            <table id="student-table" class="table-scrolls">
                <thead>
                    <tr>
                        <th class="text-center" width="45px"></th>
                        <th class="text-center" width="10%" data-sort-method='none'>
                            #
                        </th>
                        <th class="text-center data-sort fio" width="30%">
                            ФИО
                        </th>
                        <th class="text-center data-sort">
                            Группа
                        </th>
                    </tr>
                </thead>
                <tbody id="target">
                    {% for student in students %}
                    <tr>
                        <td>
                            <input id="id_student_{{ student.id }}" type="radio" name="student"
                                value="{{ student.id }}">
                        </td>
                        <td class="text-center">
                            {{ forloop.counter }}
                        </td>
                        <td class="text-center fio">
                            <a href="{% url 'student_detail' student.user.id %}">
                                {{student.user.get_full_name}}
                            </a>
                        </td>
                        <td class="text-center">
                            {{ student.group }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!-- Message if sort not date -->
            <div class="error-search text-center mt-3" style="display: none;">
                <p><i class="fa fa-exclamation-circle"></i> По вашему запросу ничего не найдено</p>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-success">Выдать</button>
            &nbsp;
            <a class="btn btn-secondary" href="{% url 'achievement' %}" class="">Назад</a>
        </div>
</form>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        $('#id_achievement').select2({
            placeholder: "",
            width: '100%'
        });
    });

    $(document).on("select2:open", () => {
        document.querySelector(".select2-container--open .select2-search__field").focus()
    })

    var info_messages = document.getElementsByClassName('alert');
    setTimeout(function () {
        for (var i = 0; i < info_messages.length; i++) {
            info_messages[i].setAttribute('style', 'display:none !important');
        }
    }, 3000);

    $("#search").on("keyup", function () {
        var inputValue = $(this).val().toLowerCase();
        var count = 0
        $("#student-table tbody tr").filter(function () {
            if ($(this).children('.fio').text().toLowerCase().indexOf(inputValue) > -1) count++;
            $(this).toggle($(this).children('.fio').text().toLowerCase().indexOf(inputValue) > -1)
        });
        if (count == 0) {
            $('.error-search').show();
        } else {
            $('.error-search').hide();
        }
    });

    filterTable(document.getElementById("target"), {
        3: document.getElementById("name-group")
    });
</script>
{% endblock %}